[project]
name = "xdsl-torch"
version = "0.1.0"
description = "Use xDSL for custom compiler rewrites in PyTorch."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["torch>=2.6.0", "xdsl>=0.29.0"]
